<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>BatteryGuardian</RootNamespace>
		<AssemblyName>BatteryGuardian</AssemblyName>
		<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
		<Platforms>AnyCPU</Platforms>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="System.Management" Version="10.0.12" />
	  <PackageReference Include="System.Speech" Version="10.0.12" />
	</ItemGroup>
	
	  <ItemGroup>
    <!-- Exclude the test project folder so it doesn't get pulled into the main assembly -->
    <Compile Remove="BatteryGuardian.Tests\**" />
    <None Remove="BatteryGuardian.Tests\**" />
    <Page Remove="BatteryGuardian.Tests\**" />
    <ApplicationDefinition Remove="BatteryGuardian.Tests\**" />
    <Resource Remove="BatteryGuardian.Tests\**" />
    <EmbeddedResource Remove="BatteryGuardian.Tests\**" />
  </ItemGroup>

</Project>